project:
  type: website
  output-dir: docs

website:
  title: "Guillaume Papuga"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: analyses.qmd
        text: Analyses
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

editor: visual

