---
title: "Teaching"
---

I am a lecturer at the [University of Montpellier](https://www.umontpellier.fr/){target="_blank"}, Faculty of Sciences, Department of Biology & Ecology.\
I teach **ecology, botany, and data analysis**, from undergraduate to graduate levels, with a strong emphasis on fieldwork and quantitative skills.

My teaching combines lectures, practicals, and project-based learning, with a strong focus on linking ecological theory to conservation practice. As a **botanist**, I regularly lead field courses in Mediterranean, temperate and alpine ecosystems, helping students develop naturalist skills and field-based ecological reasoning.

I am currently responsible for several courses in the Bachelor’s and Master’s curriculum, including two core modules in ecology.

## Master program

Together with [Anne Charpentier](https://www.cefe.cnrs.fr/fr/recherche/bc/dsse/869-c/251-anne-charpentier){target="_blank"}, I co-coordinate the [RAINET track](https://ingenieurs-ecologues.com/parcours-ge/parcours-rainet/) within the Master program *“[Biodiversity and Environmental Management](https://ingenieurs-ecologues.com/)”*.

The RAINET track is a Master’s program in conservation ecology, bridging academia and conservation organizations. It prepares students for PhD research and careers as conservation scientists or scientific project managers.

Students receive a multidisciplinary training in conservation biology and gain hands-on experience working with professionals in biodiversity conservation. The program trains ecologists to understand complex conservation challenges and develop innovative solutions.

[Key skills include:]{.underline}

-   Mastering concepts and methods in ecology, biogeography, evolutionary biology, and socio-economic aspects of conservation.

-   Collaborating effectively with conservation actors and understanding the tools and policies guiding biodiversity management.

-   Identifying ecological and social factors that influence the success of conservation programs and prioritizing species and ecosystems.

-   Designing and conducting research projects, from defining questions to analyzing results.

-   Communicating scientific findings clearly, in both French and English.

For more information, contact us!
